"""adding a film table

Revision ID: f07591821ab2
Revises: dfe0ae9d131c
Create Date: 2020-07-20 15:52:24.178315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07591821ab2'
down_revision = 'dfe0ae9d131c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('film_name', sa.String(length=128), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('imdb_link', sa.String(length=128), nullable=True),
    sa.Column('imdb_rating', sa.Float(), nullable=True),
    sa.Column('no_downloads', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('film_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('films')
    # ### end Alembic commands ###
